apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mockbin
    app.kubernetes.io/component: mockbin
    topology.istio.io/subzone: zone1
    topology.kubernetes.io/region: lab
    topology.kubernetes.io/zone: zone1
    version: v1
  name: mockbin-v1
  namespace: ns1
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: mockbin
      version: v1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mockbin
        sidecar.istio.io/inject: 'true'
        topology.istio.io/subzone: zone1
        topology.kubernetes.io/region: lab
        topology.kubernetes.io/zone: zone1
        version: v1
    spec:
      containers:
        - env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: OTEL_SPAN_SERVICE
              valueFrom:
                configMapKeyRef:
                  key: SRV_NAME
                  name: instance
            - name: ZONE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.labels['topology.kubernetes.io/zone']
            - name: REGION
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.labels['topology.kubernetes.io/region']
            - name: SUBZONE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.labels['topology.istio.io/subzone']
            - name: OTEL_PROTOCOL
              value: grpc
            - name: TZ
              value: UTC
          image: localhost/mockbin:v1.0.0
          imagePullPolicy: Always
          name: mockbin-v1
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            limits:
              cpu: '1'
              memory: 1Gi
            requests:
              cpu: 10m
              memory: 256Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        - args:
            - --config=/config/collector.yml
          image: localhost/opentelemetry-collector-contrib:0.121.0
          imagePullPolicy: Always
          name: otel
          ports:
            - containerPort: 4317
              protocol: TCP
            - containerPort: 4318
              protocol: TCP
            - containerPort: 50514
              protocol: TCP
            - containerPort: 50514
              protocol: UDP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /config/collector.yml
              name: collector
              readOnly: true
              subPath: collector.yml
      dnsPolicy: ClusterFirst
      #nodeSelector:
      #  topology.istio.io/subzone: zone1
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 3
      volumes:
        - configMap:
            defaultMode: 420
            name: instance
            optional: true
          name: instance
        - configMap:
            defaultMode: 420
            name: collector
            optional: true
          name: collector
