apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- cm.yml
- deploy.yml
- service.yml

namespace: ns1
images:
- name: localhost/mockbin
  newName: quay.io/user_name/mockbin
  newTag: v1.0.0
- name: localhost/opentelemetry-collector-contrib
  newName: quay.io/otel/opentelemetry-collector-contrib
  newTag: 0.121.0
